# 1. Numpy 행렬 기본연산 (반복문은 사용하지 않고 풀어봅시다)

- np.arange와 reshape를 이용하여 다음 행렬 A를 만들어보세요

*   항목 추가
*   항목 추가


[[1,2],[3,4],[5,6],[7,8]]

In [1]:
import numpy as np

A = np.arange(1, 9).reshape(4, 2)

A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

- A의 짝수행의 모든 요소의 합을 구하세요

In [2]:
even_rows_sum = np.sum(A[::2, :])
even_rows_sum

14

- A의 모든 요소에 5를 곱한뒤에 3을 나눴을 때 그 몫과 나머지를 구하세요

몫 = [[ 1  3]
 [ 5  6]
 [ 8 10]
 [11 13]], 
나머지 = [[2 1]
 [0 2]
 [1 0]
 [2 1]]


- A를 요소의 갯수로 나눠주세요

array([[0.16666667, 0.33333333],
       [0.5       , 0.66666667],
       [0.83333333, 1.        ]])

# 2. Numpy 행렬 다루기 (반복문은 사용하지 말고 풀어봅시다)

다음 두 행렬을 가지고 문제를 풀어봅시다 
x = np.array([2,6,9,0,1,5,4,3,7,8])
y = np.array([3,4,7,2,6,1,9,7,8,0])

- x가 3보다 크고 8보다 작은 값을 갖는 인덱스에 대응하는 y값들의 평균을 구하세요 

5.5

- 두 행렬이 세로로 결합된 새로운 행렬 xy1을 만드세요

- 두 행렬이 가로로 결합된 새로운 행렬 xy2를 만드세요

array([2, 6, 9, 0, 1, 5, 4, 3, 7, 8, 3, 4, 7, 2, 6, 1, 9, 7, 8, 0])

- x가 오름차순으로 정렬되는 순서에 대해 y는 어떻게 정렬될지 구하세요

array([2, 6, 3, 7, 9, 1, 4, 8, 0, 7])

- 이번에는 x를 내림차순으로 정렬해보세요

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 3. 복사하기

행렬 T를 변화시키지 않으면서 첫번째 요소만 1로 변경한 새 행렬 G를 만들기 위해 코드를 작성하였습니다. 
그러나 코드가 T까지 변화시키는 것을 발견하였습니다. 아래 코드의 문제점을 고쳐보세요

In [ ]:
T = np.random.random((10,10))
print(f"T의 첫번째 요소는 {T[0,0]}")
G = T
G[0,0] = 1

print(f"T의 첫번째 요소는 {T[0,0]}, G의 첫번째 요소는 {G[0,0]} ")

T의 첫번째 요소는 0.45347427722337574
T의 첫번째 요소는 1.0, G의 첫번째 요소는 1.0 


# 4. Ufunc

In [ ]:
R = np.array([[0.33, 0.29, 0.39, 0.76, 0.95],
              [0.63, 0.07, 0.93, 0.47, 0.99],
              [0.99, 0.25, 0.04, 0.92, 0.7 ],
              [0.2 , 0.27, 0.46, 0.08, 0.34],
              [0.14, 0.53, 1.  , 0.71, 0.85]])

- R행렬의 각 행별 최소값을 구하세요

array([0.29, 0.07, 0.04, 0.08, 0.14])

- 각 요소의 sin값을 구하세요

array([[0.32404303, 0.28595223, 0.38018842, 0.68892145, 0.8134155 ],
       [0.58914476, 0.06994285, 0.80161994, 0.45288629, 0.83602598],
       [0.83602598, 0.24740396, 0.03998933, 0.79560162, 0.64421769],
       [0.19866933, 0.26673144, 0.44394811, 0.07991469, 0.33348709],
       [0.13954311, 0.50553334, 0.84147098, 0.65183377, 0.75128041]])

- R행렬의 각 열별 분산값을 구하세요

array([0.099336, 0.021536, 0.127944, 0.085336, 0.055384])